# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.5

# Mod
mod_version=1.0.2
maven_group=com.juicy.discordcontroller
archives_base_name=discord-ingame-controller

# Modrinth
modrinth_project_id=xXqziNqX

# Dependencies
fabric_version=0.141.6+1.21.11
